<?php

function edor_data_import_fetch($url) {
  $cache = cache_get($url);
  if ($cache) {
    return $cache->data;
  }
  else {
    $xml = new SimpleXMLElement($url, 0, TRUE);
    $cache = theme("roster",array("roster"=>$xml));
    cache_set($url,$cache,'cache', CACHE_TEMPORARY);
    return $cache;
  }
}

function edor_data_import_theme() {
  return array(
    'roster' => array(
       'template' => 'roster',
       'variables' => array('xml' => NULL),
     ),
  );
}
